# Generated by Django 5.2.11 on 2026-02-10 05:24

import common.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=50, unique=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('Book_name', models.CharField(max_length=100)),
                ('Authors_name', models.CharField(max_length=100)),
                ('Genre', models.CharField(max_length=50)),
                ('Language', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('Roll_no', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('User_name', models.CharField(max_length=50, unique=True)),
                ('Password', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('Phn_no', models.IntegerField(unique=True)),
                ('Batch', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Book_copy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='common.book_details')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('NOT_APPROVED', 'Not Approved')], default='PENDING', max_length=20)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='common.book_copy')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.registration')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_on', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(default=common.models.overdue)),
                ('returned_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NOT_RETURNED', 'Not Returned'), ('RETURNED', 'Returned')], default='NOT_RETURNED', max_length=20)),
                ('Access_no', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='common.book_copy')),
                ('Owned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='common.registration')),
            ],
        ),
        migrations.CreateModel(
            name='Fine_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_payable', models.PositiveIntegerField()),
                ('paid', models.BooleanField(default=False)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common.transaction_table')),
            ],
        ),
    ]
