# Generated by Django 5.2.8 on 2025-12-10 05:03

import common.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ISBN', models.CharField(max_length=50, unique=True)),
                ('Book_name', models.CharField(max_length=100)),
                ('Authors_name', models.CharField(max_length=100)),
                ('Genre', models.CharField(max_length=50)),
                ('Language', models.CharField(max_length=50)),
                ('No_of_copies', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('Available_books', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('Posessed', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('Roll_no', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('User_name', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('Phn_no', models.IntegerField(unique=True)),
                ('Batch', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Book_specefic',
            fields=[
                ('Access_no', models.IntegerField(primary_key=True, serialize=False)),
                ('ISBN', models.ForeignKey(db_column='ISBN', on_delete=django.db.models.deletion.CASCADE, related_name='Bk_specific_access', to='common.book_details', to_field='ISBN')),
            ],
        ),
        migrations.CreateModel(
            name='Fine_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('Due_date', models.DateField(default=common.models.overdue)),
                ('Access_no', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fine_access', to='common.book_specefic')),
                ('Owned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='individual', to='common.registration')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('NOT_APPROVED', 'Not Approved')], default='Pending', max_length=20)),
                ('book', models.ForeignKey(db_column='ISBN', on_delete=django.db.models.deletion.CASCADE, to='common.book_details', to_field='ISBN')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.registration')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Due_date', models.DateField(default=common.models.overdue)),
                ('Status', models.CharField(choices=[('Returned', 'Returned'), ('Not_Returned', 'Not Returned')], default='Not_Returned', max_length=20)),
                ('Access_no', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_access', to='common.book_specefic')),
                ('Owned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person', to='common.registration')),
            ],
        ),
    ]
