# Generated by Django 6.0.2 on 2026-02-13 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['reserved_at']},
        ),
        migrations.RenameField(
            model_name='transaction_table',
            old_name='due_date',
            new_name='Due_date',
        ),
        migrations.RemoveField(
            model_name='transaction_table',
            name='returned_on',
        ),
        migrations.RemoveField(
            model_name='transaction_table',
            name='status',
        ),
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.EmailField(default='byragpaul98@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='allocated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction_table',
            name='collected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction_table',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction_table',
            name='returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book_details',
            name='Genre',
            field=models.CharField(choices=[('HORROR', 'horror'), ('NOVEL', 'novel'), ('POEMS', 'poems'), ('EXAM ORIENTED', 'examoriented')], max_length=50),
        ),
        migrations.AlterField(
            model_name='book_details',
            name='Language',
            field=models.CharField(choices=[('ENGLISH', 'ENGLISH'), ('MALAYALAM', 'MALAYALAM'), ('HINDI', 'HINDI')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fine_table',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finetable', to='common.transaction_table'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ALLOCATED', 'Allocated'), ('COLLECTED', 'Collected'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction_table',
            name='issued_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
