# Generated by Django 5.2.11 on 2026-02-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['reserved_at']},
        ),
        migrations.RenameField(
            model_name='transaction_table',
            old_name='due_date',
            new_name='Due_date',
        ),
        migrations.RemoveField(
            model_name='transaction_table',
            name='returned_on',
        ),
        migrations.RemoveField(
            model_name='transaction_table',
            name='status',
        ),
        migrations.AddField(
            model_name='reservation',
            name='allocated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction_table',
            name='collected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction_table',
            name='returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book_details',
            name='Genre',
            field=models.CharField(choices=[('HORROR', 'horror'), ('NOVEL', 'novel'), ('POEMS', 'poems'), ('EXAM ORIENTED', 'examoriented')], max_length=50),
        ),
        migrations.AlterField(
            model_name='book_details',
            name='Language',
            field=models.CharField(choices=[('ENGLISH', 'ENGLISH'), ('MALAYALAM', 'MALAYALAM'), ('HINDI', 'HINDI')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ALLOCATED', 'Allocated'), ('COLLECTED', 'Collected'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction_table',
            name='issued_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
