# Generated by Django 5.2.11 on 2026-02-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('BCOM', 'Bachelor of Commerce')], default='CSE', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='roles',
            field=models.CharField(choices=[('STUDENT', 'student'), ('TEACHER', 'teacher')], default='student', max_length=20),
            preserve_default=False,
        ),
    ]
