# Generated by Django 5.2.11 on 2026-02-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.EmailField(default='azvidyasagar@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
