# Generated by Django 5.2.11 on 2026-02-12 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_registration_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_table',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fine_table',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finetable', to='common.transaction_table'),
        ),
    ]
