# Generated by Django 5.2.11 on 2026-02-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_registration_department_registration_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='face_encoding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
