# Generated by Django 5.2.11 on 2026-02-16 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_registration_face_encoding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='User_name',
        ),
    ]
